name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ./src/Negotiations.WebApi/Negotiations.WebApi.csproj -c Relase -o ${{ env.DOTNET_ROOT }}/api
    - name: upload artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: api-artifact
        path: ${{ env.DOTNET_ROOT }}/api



  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Dev'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          # Artifact name
          name: api-artifact
      - name: Azure WebApp
        id: deploy-to-azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'NegotationApi'
          publish-profie: ${{ secrets.PUBLISH_PROFILE_DEV }}
